language: android
android:
  components:
  - platform-tools
  - extra
  - android-23
  - build-tools-23.0.1
script:
- gradle clean build
notifications:
  slack:
    secure: FIBbOk1EY0/Z47ZftHHmSEyrStOmk43YjMzM6Ek7F094SxaP5smwcSur91ZkKBHuTZV0FeI7GEGdaj5NDCU1cfOtmgIH4g+/TgDD3NtN+N6tzIRBpqjVwbUo+sIkEqSQ2nkCL3rYfLi8IiBLHwbVkGwOibOOeJ+BUNnOmlWsGfo=
  email:
    recipients:
    - jak@microsoft.com
    on_success: never
    on_failure: always
